In [1]:
!pip install --quiet chex

In [1]:
import jax, sys
import unittest
from functools import partial
import chex
from util import TestCase
import jax.numpy as jnp
import numpy as np
from test_flux_sector import TestFluxSector
from test_periods import TestPeriodSector
from test_complex_structure_sector import TestCSSector
sys.path.append("./../")
import jaxvacua


TODO: Add function that converts M,K fluxes to full fluxes with and without coni-LCS?


(CVXPY) Jun 24 04:37:27 PM: Encountered unexpected exception importing solver GLPK:
ImportError("cannot import name 'glpk' from 'cvxopt' (/home/cytools/cytools-venv/lib/python3.11/site-packages/cvxopt/__init__.py)")
(CVXPY) Jun 24 04:37:27 PM: Encountered unexpected exception importing solver GLPK_MI:
ImportError("cannot import name 'glpk' from 'cvxopt' (/home/cytools/cytools-venv/lib/python3.11/site-packages/cvxopt/__init__.py)")
(CVXPY) Jun 24 04:37:27 PM: Encountered unexpected exception importing solver PDLP:
RuntimeError('Version of ortools (9.6.2534) is too old. Expected >= 9.7.0.')


Test model attributes?
ADD TEST MASS MATRIX!!!!!
TODO: Choose one specific value for which we know the answer (e.g. for one of the minima which relates fluxes by gauge_kin fct!
Test model attributes?
Test model attributes?


In [2]:
suite = unittest.defaultTestLoader.loadTestsFromTestCase(TestPeriodSector)
r = unittest.TextTestRunner().run(suite)

...........

Not sure if the tests below are correct!


.

Not sure if the tests below are correct!
Should we test also the derivative along X0?


..

Should we test also the derivative along X0?


..
----------------------------------------------------------------------
Ran 16 tests in 125.268s

OK


In [2]:
suite = unittest.defaultTestLoader.loadTestsFromTestCase(TestCSSector)
r = unittest.TextTestRunner().run(suite)

Can be copied to periods!


.

Can be copied to periods!


.....................
----------------------------------------------------------------------
Ran 22 tests in 163.136s

OK


In [3]:
suite = unittest.defaultTestLoader.loadTestsFromTestCase(TestFluxSector)
r = unittest.TextTestRunner().run(suite)

E
ERROR: setUpClass (test_flux_sector.TestFluxSector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cytools/mounted_volume/Software/GitHub/JAX_StringVacua/tests/test_flux_sector.py", line 57, in setUpClass
    res = root(cls.model.fterms,x0=x0,args=(cls.f_solution,),method="hybr",jac=cls.model.fterms_jacobian)
               ^^^^^^^^^^^^^^^^
AttributeError: 'flux_sector' object has no attribute 'fterms'

----------------------------------------------------------------------
Ran 0 tests in 0.803s

FAILED (errors=1)


In [5]:
h12=2
model = jaxvacua.flux_sector(h12=2,model_ID=1,model_type="KS",maximum_degree=5)
z = jnp.array(np.random.uniform(-1,1,h12)+1j*np.random.uniform(0,10,h12))
cz = jnp.conj(z)
tau = np.random.uniform(1,2)+1j*np.random.uniform(0.1,0.5)
ctau = jnp.conj(tau)
f = jnp.array(np.random.randint(-10,11,4*(h12+1)))

XPer = jnp.append(jnp.ones(1),z)
cXPer = jnp.conj(XPer)

tau_fd,f_fd,sig = model.map_to_FD_tau(tau,f,return_SL2Z_matrix=True)

ctau_fd = jnp.conj(tau_fd)

Could include some optional arguments in **kwargs?
For input period/prepotential, we should have a function that checks validity of solution                 (i.e., sth. like in region of convergence?). That is, replacing hyperplanes check in the LCS region...
Convert input of private CYTools at a later stage!
GV or GW invariants to be used????
No grading vector provided!
Gauge choice????
Change name of some conj function!!!
TODO: Provide optional input for superpotential?
This could be part of separate script!


/home/cytools/mounted_volume/Software/GitHub/JAX_StringVacua/tests/./../jaxvacua/flux_sector.py:146: UserWarning: Can this made jit compatible?
  warnings.warn("Can this made jit compatible?")


In [8]:
KM = model.kahler_metric(z,cz,tau,ctau)
eigvals = jnp.linalg.eigvals(KM)
jnp.min(eigvals.real)/jnp.min(jnp.abs(eigvals.real))

Array(1., dtype=float64)

In [9]:
t1 = model.periods.grad_kahler_potential_per(XPer,cXPer,conj=False)[:,None]*model.periods.period_vector_per(XPer,conj=False)
t2 = jnp.outer(model.periods.period_vector_per(XPer,conj=False),model.periods.grad_kahler_potential_per(XPer,cXPer,conj=False))
t1.T-t2

Array([[0.+2.22044605e-16j, 0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+1.77635684e-15j, 0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+1.73472348e-18j]],      dtype=complex128)

In [6]:
N_c = model.gauge_kinetic_matrix(z,cz,conj=True)
N = model.gauge_kinetic_matrix(z,cz,conj=False)
N-jnp.conj(N_c)

PROBABLY HAVE TO FIX CONJUGATION INSIDE Q AND P!!
TODO: Combine P and Q in one function?!


Array([[ 0.00000000e+00+0.0000000e+00j,  0.00000000e+00+0.0000000e+00j,
         0.00000000e+00+8.8817842e-16j],
       [ 0.00000000e+00+0.0000000e+00j,  4.44089210e-16+0.0000000e+00j,
         2.22044605e-16+0.0000000e+00j],
       [ 0.00000000e+00+0.0000000e+00j,  0.00000000e+00+0.0000000e+00j,
        -1.11022302e-16+0.0000000e+00j]], dtype=complex128)

In [5]:
dN_X = model.gauge_kinetic_matrix_grad_periods(z,cz,conj=False)
dN_cX_c = model.gauge_kinetic_matrix_grad_cperiods(z,cz,conj=True)
dN_X_c = model.gauge_kinetic_matrix_grad_periods(z,cz,conj=True)
dN_X,dN_cX_c,dN_X_c
#dN_X - jnp.conj(dN_X_c)
dN_X - jnp.conj(dN_cX_c)

Array([[[ 1.06581410e-14+5.68434189e-14j,
          0.00000000e+00-1.77635684e-15j,
          0.00000000e+00-2.63677968e-16j],
        [ 1.42108547e-14+8.88178420e-16j,
          4.44089210e-16+0.00000000e+00j,
          0.00000000e+00+0.00000000e+00j],
        [ 3.55271368e-15-4.44089210e-16j,
          0.00000000e+00+0.00000000e+00j,
          0.00000000e+00+0.00000000e+00j]],

       [[ 0.00000000e+00+1.77635684e-15j,
          1.11022302e-16+0.00000000e+00j,
          2.22044605e-16+0.00000000e+00j],
        [-8.88178420e-16+1.42108547e-14j,
          0.00000000e+00-1.11022302e-16j,
          0.00000000e+00-1.11022302e-16j],
        [-3.88578059e-16+1.77635684e-15j,
          0.00000000e+00-5.55111512e-17j,
          0.00000000e+00-6.93889390e-18j]],

       [[ 0.00000000e+00+2.22044605e-16j,
          1.52655666e-16+0.00000000e+00j,
          4.16333634e-17+2.22044605e-16j],
        [ 4.44089210e-16-1.77635684e-15j,
          0.00000000e+00+4.16333634e-17j,
          0.00000000e+0

In [10]:
#model.kahler_potential(z,cz,tau,ctau),model.kahler_potential(cz,z,ctau,tau)
model.dK_z(z,cz,tau,ctau),model.dK_cz(z,cz,tau,ctau)

(Array([ 5.62050406e-15+0.27408096j, -4.70921944e-07+0.09093345j],      dtype=complex128),
 Array([ 5.62050406e-15-0.27408096j, -4.70921944e-07-0.09093345j],      dtype=complex128))

In [12]:
model.ddK_z_cz(z,cz,tau,ctau)-jnp.conj(model.ddK_z_cz(z,cz,tau,ctau).T)#,model.ddK_z_ctau(z,cz,tau,ctau)
#model.ddK_tau_ctau(z,cz,tau,ctau)-jnp.conj(model.ddK_tau_ctau(z,cz,tau,ctau))
jnp.linalg.eigvals(model.kahler_metric(z,cz,tau,ctau))

Array([1.09402799e+01+1.11047927e-15j, 4.06022169e-03-2.56244980e-19j,
       1.36474555e+01+0.00000000e+00j], dtype=complex128)

In [50]:
from scipy.optimize import root
moduli = z
x0 = jnp.array([jnp.real(moduli[0]),jnp.imag(moduli[0]),jnp.real(moduli[1]),jnp.imag(moduli[1]),jnp.real(tausol),jnp.imag(tausol)])
res = root(model.fterms,x0=x0,args=(Fcc,),method="hybr",jac=model.fterms_jacobian)
res


 message: The solution converged.
 success: True
  status: 1
     fun: [ 0.000e+00  2.502e-14  0.000e+00  5.640e-14 -2.887e-34
            1.619e-14]
       x: [-7.602e-25  2.742e+00 -5.702e-25  2.057e+00 -1.900e-24
            6.855e+00]
    nfev: 3
    njev: 1
    fjac: [[-8.571e-01  1.032e-24 ...  4.286e-01 -7.021e-31]
           [-9.473e-25 -8.571e-01 ...  4.737e-25  4.286e-01]
           ...
           [-3.578e-01 -3.869e-20 ... -8.944e-01 -9.672e-20]
           [ 3.869e-20 -3.578e-01 ...  9.672e-20 -8.944e-01]]
       r: [-7.000e+00  7.736e-24 ...  1.608e-24  1.127e-05]
     qtf: [-3.570e-32 -1.860e-13 -1.064e-32  4.440e-13  7.456e-32
            5.797e-16]

In [60]:
res.success==True

True

In [52]:
x = res.x
u1sol = x[0]+1j*x[1]
u2sol = x[2]+1j*x[3]
tausol = x[4]+1j*x[5]

In [53]:
z = jnp.array([u1sol,u2sol])
cz = jnp.conj(z)
tau = tausol
ctau = jnp.conj(tau)
f = Fcc

In [11]:
DDW_z_cz = model.DDW_z_cz(z,cz,tau,ctau,f,conj=False)
DDW_cz_z = model.DDW_z_cz(z,cz,tau,ctau,f,conj=True)
dDW_cz_c = model.dDW_z(z,cz,tau,ctau,f,conj=True)
dDW_cz = model.dDW_cz(z,cz,tau,ctau,f,conj=False)
dDW_z_c = model.dDW_cz(z,cz,tau,ctau,f,conj=True)
dDW_z = model.dDW_z(z,cz,tau,ctau,f,conj=False)

In [22]:
dDW = model.dDW(z,cz,tau,ctau,f,conj=False)
dDW_c = model.dDW_c(z,cz,tau,ctau,f,conj=False)
dDW_cc = model.dDW(z,cz,tau,ctau,f,conj=True)
dDW_c_cc = model.dDW_c(z,cz,tau,ctau,f,conj=True)
dDW-jnp.conj(dDW_cc),dDW_c-jnp.conj(dDW_c_cc),dDW_cc,dDW_c_cc

(Array([[ 1.13686838e-13-1.13686838e-13j,  0.00000000e+00-2.84217094e-14j,
          0.00000000e+00+0.00000000e+00j],
        [ 2.84217094e-14-2.84217094e-14j, -7.10542736e-15+0.00000000e+00j,
          0.00000000e+00+0.00000000e+00j],
        [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
          0.00000000e+00+0.00000000e+00j]], dtype=complex128),
 Array([[9.94759830e-14-9.94759830e-14j, 0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j],
        [2.13162821e-14-1.42108547e-14j, 1.77635684e-15+1.77635684e-15j,
         0.00000000e+00+0.00000000e+00j],
        [0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j]], dtype=complex128),
 Array([[-7.29508114e+01-4.29218068e+02j, -1.97693528e+01-1.51134203e+02j,
         -2.64631844e+03+2.88905102e+02j],
        [-2.71775145e+01-1.49681928e+02j, -8.94998049e+00-3.07718296e+01j,
         -8.41548610e+02+1.21907371e+02j],
        [ 1.77808227e+03+

In [12]:
dDW_z,dDW_z_c

(Array([[ -3.01157565 +211.85434186j,   6.6587386   +75.80801617j],
        [ -2.87581274  +81.02768448j,  -2.06434251  +10.29642695j],
        [233.34758901-3077.34950646j, 126.49128247 -907.22355046j]],      dtype=complex128),
 Array([[25.0039016 +93.87961586j,  4.83090219+18.14262118j],
        [ 4.83315152+18.1420221j ,  2.52609459 +9.48447141j],
        [ 0.         +0.j        ,  0.         +0.j        ]],      dtype=complex128))

In [13]:
dDW_cz,dDW_cz_c

(Array([[25.0039016 -93.87961586j,  4.83090219-18.14262118j],
        [ 4.83315152-18.1420221j ,  2.52609459 -9.48447141j],
        [ 0.         +0.j        ,  0.         +0.j        ]],      dtype=complex128),
 Array([[ -3.01157565 -211.85434186j,   6.6587386   -75.80801617j],
        [ -2.87581274  -81.02768448j,  -2.06434251  -10.29642695j],
        [233.34758901+3077.34950646j, 126.49128247 +907.22355046j]],      dtype=complex128))

In [16]:
dDW_z-jnp.conj(dDW_cz_c),dDW_z_c-jnp.conj(dDW_cz)

(Array([[ 2.84217094e-14+0.00000000e+00j,  0.00000000e+00+2.84217094e-14j],
        [ 1.06581410e-14+0.00000000e+00j, -1.77635684e-15+3.55271368e-15j],
        [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j]],      dtype=complex128),
 Array([[7.10542736e-15+2.84217094e-14j, 2.39808173e-14+1.06581410e-14j],
        [7.99360578e-15+3.55271368e-15j, 1.77635684e-15+5.32907052e-15j],
        [0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j]],      dtype=complex128))

In [6]:
DDW_cz_z-DDW_z_cz

Array([[8.17124146e-14-222.07057715j, 1.95399252e-14 -79.4932709j ],
       [8.88178420e-15 -89.93256349j, 0.00000000e+00 -16.68781378j]],      dtype=complex128)

In [56]:
jnp.conj(DDW_z_cz), DDW_z_cz.T,DDW_z_cz

(Array([[-1.31356123e-07-0.00000000e+00j, -3.85012166e-08-0.00000000e+00j],
        [-3.85011955e-08+1.80517565e-24j, -1.70307062e-08-0.00000000e+00j]],      dtype=complex128),
 Array([[-1.31356123e-07+0.00000000e+00j, -3.85011955e-08-1.80517565e-24j],
        [-3.85012166e-08+0.00000000e+00j, -1.70307062e-08+0.00000000e+00j]],      dtype=complex128),
 Array([[-1.31356123e-07+0.00000000e+00j, -3.85012166e-08+0.00000000e+00j],
        [-3.85011955e-08-1.80517565e-24j, -1.70307062e-08+0.00000000e+00j]],      dtype=complex128))

In [8]:
jnp.conj(DDW_z_cz)-DDW_cz_z
#jnp.conj(DDW_z_cz)-DDW_z_cz.T
#DDW_z_cz.T-DDW_z_cz

Array([[-8.17124146e-14+2.84217094e-14j, -1.95399252e-14-1.42108547e-14j],
       [-8.88178420e-15+2.13162821e-14j,  0.00000000e+00+0.00000000e+00j]],      dtype=complex128)

In [58]:
DDW_z_cz-model.kahler_metric(z,cz,tau,ctau)[:-1,:-1]*model.superpotential(z,tau,f)

Array([[1.09187618e-14+0.j, 3.49400379e-15+0.j],
       [2.46107937e-14+0.j, 7.87545399e-15+0.j]], dtype=complex128)

In [59]:
self = model
conj = False
moduli = z
moduli_c = cz
tau_c = ctau
fluxes = f

DW = self.DW_z(moduli,moduli_c,tau,tau_c,fluxes,conj=conj)

if conj:
    KDW = jnp.outer(DW,self.dK_z(moduli,moduli_c,tau,tau_c))
else:
    KDW = jnp.outer(DW,self.dK_cz(moduli,moduli_c,tau,tau_c))

self.dDW_z_cz(moduli,moduli_c,tau,tau_c,fluxes,conj=conj),KDW

(Array([[-1.31356134e-07+0.00000000e+00j, -3.85012201e-08+0.00000000e+00j],
        [-3.85012201e-08-1.80517565e-24j, -1.70307140e-08+0.00000000e+00j]],      dtype=complex128),
 Array([[1.09187618e-14+0.j, 3.49400379e-15+0.j],
        [2.46107937e-14+0.j, 7.87545398e-15+0.j]], dtype=complex128))

In [47]:
DW,self.dK_cz(moduli,moduli_c,tau,tau_c)

(Array([230.02435289+18.57211853j,  54.36201868+19.15021856j], dtype=complex128),
 Array([2.45636844e-15-0.19500013j, 0.00000000e+00-0.05564603j],      dtype=complex128))

In [48]:
self.dK_z(moduli,moduli_c,tau,tau_c)

Array([ 2.44942955e-15+0.19500013j, -1.73472348e-18+0.05564603j],      dtype=complex128)

In [52]:
W = model.superpotential_gauge_invariant(z,tau,f,conj=False)
W_fd = model.superpotential_gauge_invariant(z,tau_fd,f_fd,conj=False)

Is this function (and its derivatives) faster when                we use the expression in terms of  prepotential????


In [53]:
W,W_fd

(Array(41.90201875-42.40842113j, dtype=complex128),
 Array(57.67675418-15.08792187j, dtype=complex128))

In [54]:
sig[0][0]*f[:model.NumFluxes]+sig[0][1]*f[model.NumFluxes:],sig[1][0]*f[:model.NumFluxes]+sig[1][1]*f[model.NumFluxes:]

(Array([ 30., -29.,  36., -39.,   1.,   0.], dtype=float64),
 Array([-18.,  16., -22.,  23.,  -2.,  -2.], dtype=float64))

In [55]:
f_fd

array([ 30., -29.,  36., -39.,   1.,   0., -18.,  16., -22.,  23.,  -2.,
        -2.])

In [56]:
(sig[0][0]*tau+sig[0][1])/(sig[1][0]*tau+sig[1][1])

(-0.49192845905289745+0.8948714014288426j)

In [57]:
tau_fd,f,f_fd

(Array(-0.49192846+0.8948714j, dtype=complex128, weak_type=True),
 Array([  6, -10,   6,  -9,  -4,  -6,  -6,   3,  -8,   7,  -3,  -4], dtype=int64),
 array([ 30., -29.,  36., -39.,   1.,   0., -18.,  16., -22.,  23.,  -2.,
         -2.]))

In [58]:
moduli = z

KP1 = model.kahler_potential(moduli,jnp.conj(moduli),tau,jnp.conj(tau))

W1=jnp.exp(KP1/2.)*jnp.sqrt(2./jnp.pi)*model.superpotential(moduli,tau,f,conj=False)

In [59]:
moduli = z
KP2 = model.kahler_potential(moduli,jnp.conj(moduli),tau_fd,jnp.conj(tau_fd))

W2=jnp.exp(KP2/2.)*jnp.sqrt(2./jnp.pi)*model.superpotential(moduli,tau_fd,jnp.array(f_fd),conj=False)

In [76]:
jnp.abs(W1)/jnp.abs(W2)
#W1/jnp.exp(KP1.real/2.),W2/jnp.exp(KP2.real/2.)
#jnp.exp(KP1.real/2.)/jnp.exp(KP2.real/2.)

Array(1., dtype=float64)

In [69]:
div = (sig[1][0]*tau+sig[1][1])*(sig[1][0]*jnp.conj(tau)+sig[1][1])
1/jnp.sqrt(div)

Array(1.75358906+3.00330354e-17j, dtype=complex128)

In [19]:
Fcc=jnp.array([7, 3, -24, 0, -16, 50,0, 3, -4, 0, 0, 0])

#We look for the following solutions:
u1sol=2.74215479602462524879172086700112955631003945168828832743217138983767*1j
u2sol=2.05661613496943436323419976712599580262262253939859294519039244649420*1j
tausol=6.85540179778358427172610564536555609784128313762349971439377181031816*1j

In [5]:
moduli = jnp.array([u1sol,u2sol])
fluxes = Fcc

KP = model.kahler_potential(moduli,jnp.conj(moduli),tausol,jnp.conj(tausol))

jnp.exp(KP.real/2.)*jnp.sqrt(2./jnp.pi)*model.superpotential(moduli,tausol,fluxes,conj=False)

Array(-2.03710583e-08+0.j, dtype=complex128)

In [4]:
Fcc=jnp.array([7, 3, -24, 0, -16, 50,0, 3, -4, 0, 0, 0])
moduli = z
tausol = tau

In [5]:
ddV_real = model.gradV_jacobian(jnp.array([jnp.real(moduli[0]),jnp.imag(moduli[0]),jnp.real(moduli[1]),jnp.imag(moduli[1]),jnp.real(tausol),jnp.imag(tausol)]),Fcc)
ddV_real

Array([[ 2.56341345e+00, -9.30401686e+00, -1.85463060e+01,
         5.61299565e-01,  4.50061671e+00, -4.86010405e+01],
       [-9.30401686e+00,  7.31634301e+02,  5.07500779e+01,
        -2.29048030e+02, -1.13810590e+01,  1.87919323e+03],
       [-1.85463060e+01,  5.07500779e+01,  2.46786297e+02,
         1.82073612e+01, -6.66187195e+01,  6.86580808e+02],
       [ 5.61299565e-01, -2.29048030e+02,  1.82073612e+01,
         7.68073669e+01, -5.68567060e+00, -2.59965777e+03],
       [ 4.50061671e+00, -1.13810590e+01, -6.66187195e+01,
        -5.68567060e+00,  1.81856986e+01, -1.86475302e+02],
       [-4.86010405e+01,  1.87919323e+03,  6.86580808e+02,
        -2.59965777e+03, -1.86475302e+02,  8.37866168e+04]],      dtype=float64)

In [6]:
hess_SUSY = model._scalar_potential_hessian_SUSY(moduli,jnp.conj(moduli),tausol,jnp.conj(tausol),Fcc)
hess_SUSY

Array([[  83.00749437-2.12565111e-15j,  -32.21125665-1.19497698e+01j,
         234.74929158-8.61725482e+00j,   33.35192802-1.68590918e+00j,
          11.11781186-5.59996903e-01j,  179.52426646+8.39836718e-01j],
       [ -32.21125665+1.19497698e+01j,  122.29012323-1.52411125e-14j,
        -136.00282745+4.38113242e+01j,   11.11781186-5.59996903e-01j,
         -13.71789742+4.47997523e+00j,   48.99162491-1.11999381e+00j],
       [ 234.74929158+8.61725482e+00j, -136.00282745-4.38113242e+01j,
        1482.46831673+8.64293715e-14j,  179.52426646+8.39836718e-01j,
          48.99162491-1.11999381e+00j,    0.        +0.00000000e+00j],
       [  33.35192802+1.68590918e+00j,   11.11781186+5.59996903e-01j,
         179.52426646-8.39836718e-01j,   83.00749437+2.12565111e-15j,
         -32.21125665+1.19497698e+01j,  234.74929158+8.61725482e+00j],
       [  11.11781186+5.59996903e-01j,  -13.71789742-4.47997523e+00j,
          48.99162491+1.11999381e+00j,  -32.21125665-1.19497698e+01j,
         122.290

In [10]:
hess_gen = model._scalar_potential_hessian_general(moduli,jnp.conj(moduli),tausol,jnp.conj(tausol),Fcc)
hess_gen

Array([[ 1.72486054e+00+8.99280650e-15j, -2.38525634e+00+2.41627569e-01j,
         6.81377891e+00+1.79959561e+00j, -1.05255737e+00-1.11401092e-01j,
         9.36414785e-01+2.24068691e-01j, -6.64804770e+00-1.89474405e+00j],
       [-2.38525634e+00-2.41627569e-01j,  5.21159443e+01-9.04831765e-15j,
        -6.44230027e+02-1.41508338e+01j,  9.36414785e-01+2.24068691e-01j,
         4.80896609e+01+5.40252908e-01j,  6.14747882e+02+1.39957815e+01j],
       [ 6.81377891e+00-1.79959561e+00j, -6.44230027e+02+1.41508338e+01j,
         3.16905645e+04-2.43405296e-12j, -6.64804770e+00-1.89474405e+00j,
         6.14747882e+02+1.39957815e+01j, -3.16817861e+04-6.96624873e+00j],
       [-1.05255737e+00+1.11401092e-01j,  9.36414785e-01-2.24068691e-01j,
        -6.64804770e+00+1.89474405e+00j,  1.72486054e+00-8.99280650e-15j,
        -2.38525634e+00-2.41627569e-01j,  6.81377891e+00-1.79959561e+00j],
       [ 9.36414785e-01-2.24068691e-01j,  4.80896609e+01-5.40252908e-01j,
         6.14747882e+02-1.39957815

In [7]:
eigs1 = jnp.linalg.eigvals(ddV_real)
eigs2 = jnp.linalg.eigvals(hess_SUSY)
eigs1,eigs2

(Array([ 8.39160896e+04+0.j,  7.30151620e+02+0.j,  2.66140397e+02+0.j,
         1.33727205e+00+0.j, -1.28754508e-02+0.j, -5.11121223e+01+0.j],      dtype=complex128),
 Array([1.60499296e+03+1.10562991e-14j, 1.51146131e+03-1.32430273e-14j,
        3.63076233e-01-2.47877675e-14j, 2.99463958e+01-3.74208768e-14j,
        1.26873336e+02+6.71047351e-16j, 1.01894782e+02-2.35017229e-15j],      dtype=complex128))

In [64]:
jnp.sort(eigs1.real)-jnp.sort(eigs2.real)

Array([-1.77807607e+02, -1.16365779e+01, -3.95368427e+02, -1.54337320e+02,
       -1.88645846e+03,  1.07101074e+06], dtype=float64)

In [ ]:
test = TestCase()
test.assertAllClose(eigs2,0., rtol=1e-11, atol=1e-11)

In [65]:
jnp.sort(eigs1.real)-jnp.sort(eigs2.real)*2

Array([-1.78893613e+02, -2.32736330e+01, -8.03166413e+02, -5.68400877e+02,
       -4.74942777e+03,  1.06813391e+06], dtype=float64)

In [12]:
eigs3 = jnp.linalg.eigvals(hess_gen)
eigs3

Array([ 6.33973700e+04+2.95998288e-12j,  1.08905650e+02+1.14768185e-13j,
       -2.13743238e+01-1.78194954e-13j,  3.16408633e+00-5.22941109e-14j,
        7.45146324e-01+6.77589485e-14j, -2.59729031e-12+5.65003489e-13j],      dtype=complex128)

In [67]:
jnp.sort(eigs1.real)-jnp.sort(eigs3.real)*2,jnp.sort(eigs2.real)-jnp.sort(eigs3.real)

(Array([ 1.67972303e-11,  2.98266035e-11,  1.45341517e-11, -3.27986527e-11,
         2.04522621e-10,  9.31322575e-10], dtype=float64),
 Array([ 8.94468064e+01,  1.16368165e+01,  4.01583206e+02,  2.84200438e+02,
         2.37471388e+03, -5.34066955e+05], dtype=float64))

In [68]:
jnp.max(jnp.abs(hess_SUSY-hess_gen))

Array(268391.59692345, dtype=float64)

In [69]:
eigs1.real,eigs3.real

(Array([ 1.07388756e+06,  9.76510845e+02,  2.59726236e+02, -1.76721601e+02,
         1.24295581e+01,  4.77125346e-04], dtype=float64),
 Array([ 5.36943782e+05,  4.88255423e+02,  1.29863118e+02, -8.83608005e+01,
         6.21477907e+00,  2.38562658e-04], dtype=float64))

In [6]:
dV_real = model.gradV(jnp.array([0.,jnp.imag(u1sol),0.,jnp.imag(u2sol),0.,jnp.imag(tausol)]),Fcc)
dV_real

Array([-9.40322187e-27,  5.05370714e-11,  1.00974310e-28, -2.52558836e-09,
       -2.29588740e-41,  7.37483269e-10], dtype=float64)

In [13]:
test = TestCase()
test.assertAllClose(dV_real, 0., rtol=1e-08, atol=1e-08)

In [42]:
eigvals =jnp.linalg.eigvals(ddV_real) 
jnp.min(eigvals.real)/jnp.min(jnp.abs(eigvals.real))
jnp.sign(eigvals.real)

Array([1., 1., 1., 1., 1., 1.], dtype=float64)

In [132]:
model.superpotential(moduli,tausol,fluxes,conj=False)

Array(-2.08119229e-06+41.13232285j, dtype=complex128)

In [133]:
model.superpotential(moduli,tausol,fluxes,conj=True)

Array(2.69315572e+45+41.13232285j, dtype=complex128)

In [122]:
jnp.allclose(-2.03710583e-08, -2.04e-08, rtol=1e-20, atol=1e-20)

Array(False, dtype=bool)

In [4]:
model.dDW_z_cz(z,cz,tau,ctau,f,conj=False)

TODO: TEST AND ADD COMPLEX CONJUGATE!!
TODO: SHOULD WE USE SIMPLIFIED VERSION HERE?            NO: COMPUTE DERIVATES AND USE THIS AS SIMPLIFIED EXPRESSION TEST!
Is this function (and its derivatives) faster when                we use the expression in terms of  prepotential????


Array([[-64.37183618-36.33602257j, -20.74877567-11.71207823j],
       [-20.74877567-11.71207823j,  -8.18158728 -4.61826721j]],      dtype=complex128)

In [5]:
model.dDW_z_cz(z,cz,tau,ctau,f,conj=True)

TODO: TEST AND ADD COMPLEX CONJUGATE!!
TODO: SHOULD WE USE SIMPLIFIED VERSION HERE?            NO: COMPUTE DERIVATES AND USE THIS AS SIMPLIFIED EXPRESSION TEST!


Array([[-64.37183618+36.33602257j, -20.74877567+11.71207823j],
       [-20.74877567+11.71207823j,  -8.18158728 +4.61826721j]],      dtype=complex128)

In [6]:
model.dDW_z_z(z,cz,tau,ctau,f,conj=True)

TODO: TEST AND ADD COMPLEX CONJUGATE!!


Array([[-20.92231095-94.95396448j,  -5.50256565-33.6068282j ],
       [ -6.74880826-32.04308426j,  -4.91052895 -8.7799507j ]],      dtype=complex128)

In [7]:
model.dDW_z_z(z,cz,tau,ctau,f,conj=False)

TODO: TEST AND ADD COMPLEX CONJUGATE!!


Array([[-20.92231095+94.95396448j,  -5.50256565+33.6068282j ],
       [ -6.74880826+32.04308426j,  -4.91052895 +8.7799507j ]],      dtype=complex128)

In [13]:
km = model.ddK_z_cz(z,cz,tau,ctau)
dDW = km*model.superpotential(z,tau,f,conj=False)
dDW_c = km.T*model.superpotential(cz,ctau,f,conj=True)

In [14]:
km,dDW,dDW_c

(Array([[0.14495224+0.00000000e+00j, 0.0065    -5.38588969e-06j],
        [0.0065    +5.38588969e-06j, 0.00400899+4.33680869e-19j]],      dtype=complex128),
 Array([[-199.21378291-4.74710924j,   -8.93339766-0.20546966j],
        [  -8.93304489-0.22027375j,   -5.50971516-0.13129222j]],      dtype=complex128),
 Array([[-199.21378291+4.74710924j,   -8.93339766+0.20546966j],
        [  -8.93304489+0.22027375j,   -5.50971516+0.13129222j]],      dtype=complex128))

In [9]:
model.ddK_z_ctau(z,cz,tau,ctau)

Array([0.+0.j, 0.+0.j], dtype=complex128)

In [28]:
self = model
fluxes = Fcc
tau = tausol
tau_c = jnp.conj(tau)
moduli = jnp.array([u1sol,u2sol])
moduli_c = jnp.conj(moduli)

FF = fluxes[:self.NumFluxes]
HF = fluxes[self.NumFluxes:]

G = FF-tau*HF
cG = FF-tau_c*HF

tau2 = -1j*(tau-tau_c)/2.

NFlux = self.tadpole(fluxes)

M = self.ISD_matrix(moduli,moduli_c)
M = jnp.linalg.inv(M)

t1,t2,t3=-jnp.matmul(cG,jnp.matmul(M,G))/tau2,2.*NFlux,1j*jnp.matmul(cG,jnp.matmul(self.periods.sigma(),G))/tau2
V = model.scalar_potential(moduli,moduli_c,tau,tau_c,fluxes)
V.real

Array(1.07722321e-19, dtype=float64)

In [29]:
(t1.real+t2),V.real

(Array(-1.13686838e-13, dtype=float64), Array(1.07722321e-19, dtype=float64))

In [30]:
t1,t2,t3,tau2,1/tau2

(Array(-496.-0.j, dtype=complex128),
 Array(496., dtype=float64, weak_type=True),
 Array(496.+0.j, dtype=complex128, weak_type=True),
 Array(6.8554018-0.j, dtype=complex128, weak_type=True),
 Array(0.14587037+0.j, dtype=complex128, weak_type=True))

In [26]:
t1/4,t2

(Array(-508.50608567+4.97506234e-14j, dtype=complex128),
 Array(496., dtype=float64, weak_type=True))

In [96]:
V.real

Array(5723.89677989, dtype=float64)

In [97]:
t1.real

Array(42203.22138728, dtype=float64)

In [11]:
cG@(M@G)/tau2

Array(2034.02434267-1.99002494e-13j, dtype=complex128)

In [12]:
(G@M.T).T@cG/tau2

Array(2034.02434267-1.99002494e-13j, dtype=complex128)

In [27]:
-jnp.matmul(cG,jnp.matmul(jnp.linalg.inv(M),G))/tau2

Array(-496.-0.j, dtype=complex128)

In [123]:
FT = self.DW(moduli, moduli_c, tau, tau_c, fluxes)

cFT = self.DW(moduli, moduli_c, tau, tau_c, fluxes,conj=True)

Inv_KM = self.inverse_kahler_metric(moduli, moduli_c, tau, tau_c)

KP = self.kahler_potential(moduli, moduli_c, tau, tau_c)

jnp.exp(KP) * jnp.matmul(cFT, jnp.matmul(Inv_KM, FT))

Array(33.74572932-1.66867454e-14j, dtype=complex128)

In [124]:
FT

Array([-20.94920541+5.46799456e-10j,  18.25625426+1.56134212e-09j,
        -2.99999359+1.17165726e-11j], dtype=complex128)

In [31]:
from jax.typing import ArrayLike
from jax import Array

In [104]:
def DW(x,cx,t,ct,fluxes,conj=True):
    
    imx = -(x-cx)*1j/2
    rex = (x+cx)/2
    imt = -(t-ct)*1j/2
    ret = (t+ct)/2
    
    #return jnp.array([rex[0]+1j*imx[0],rex[1]+1j*imx[1],ret+1j*imt])
    #return jnp.array([rex[0]**2,rex[1],ret])
    #return jnp.array([x[0]**2,x[1],t])
    if conj:
        return jnp.array([cx[0]**2,cx[1],ct])
    else:
        return jnp.array([x[0]**2,x[1],t])


def dDW_z(
    moduli: ArrayLike, moduli_c: ArrayLike, tau: complex, tau_c: complex, 
    fluxes: ArrayLike, conj: bool = False
    ) -> Array:

    return jax.jacfwd(DW,argnums=0,holomorphic=True)(moduli,moduli_c,tau,tau_c,fluxes,conj=conj)


def dDW_tau(
    moduli: ArrayLike, moduli_c: ArrayLike, tau: complex, tau_c: complex, 
    fluxes: ArrayLike, conj: bool = False
    ) -> Array:
    

    return jax.jacfwd(DW,argnums=2,holomorphic=True)(moduli,moduli_c,tau,tau_c,fluxes,conj=conj)

    
def dDW(
    moduli: ArrayLike, moduli_c: ArrayLike, tau: complex, tau_c: complex, 
    fluxes: ArrayLike, conj: bool = False
    ) -> Array:


    dDWz = dDW_z(moduli,moduli_c,tau,tau_c,fluxes,conj=conj)
    dDWtau = dDW_tau(moduli,moduli_c,tau,tau_c,fluxes,conj=conj)

    return jnp.append(dDWz,jnp.array([dDWtau]).T,axis=1)


def dDW_cz(
    moduli: ArrayLike, moduli_c: ArrayLike, tau: complex, tau_c: complex, 
    fluxes: ArrayLike, conj: bool = False
    ) -> Array:

    return jax.jacfwd(DW,argnums=1,holomorphic=True)(moduli,moduli_c,tau,tau_c,fluxes,conj=conj)


def dDW_ctau(
    moduli: ArrayLike, moduli_c: ArrayLike, tau: complex, tau_c: complex, 
    fluxes: ArrayLike, conj: bool = False
    ) -> Array:

    return jax.jacfwd(DW,argnums=3,holomorphic=True)(moduli,moduli_c,tau,tau_c,fluxes,conj=conj)


def dDW_c(
    moduli: ArrayLike, moduli_c: ArrayLike, tau: complex, tau_c: complex, 
    fluxes: ArrayLike, conj: bool = False
    ) -> Array:


    dDWz = dDW_cz(moduli,moduli_c,tau,tau_c,fluxes,conj=conj)
    dDWtau = dDW_ctau(moduli,moduli_c,tau,tau_c,fluxes,conj=conj)

    return jnp.append(dDWz,jnp.array([dDWtau]).T,axis=1)


In [115]:
z = jnp.array([1+1j*2.,3+1j*6.])
cz = jnp.conj(z)
tau = 5.+1j*10.
ctau = jnp.conj(tau)
conj=True

In [116]:
DW(z,cz,tau,ctau,1,conj=conj)

Array([-3. -4.j,  3. -6.j,  5.-10.j], dtype=complex128)

In [117]:
dDW_z(z,cz,tau,ctau,1,conj=conj)

Array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]], dtype=complex128)

In [118]:
dDW_tau(z,cz,tau,ctau,1,conj=conj)

Array([0.+0.j, 0.+0.j, 0.+0.j], dtype=complex128)

In [119]:
dDW(z,cz,tau,ctau,1,conj=conj)

Array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]], dtype=complex128)

In [120]:
dDW_cz(z,cz,tau,ctau,1,conj=conj)

Array([[2.-4.j, 0.+0.j],
       [0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j]], dtype=complex128)

In [121]:
dDW_ctau(z,cz,tau,ctau,1,conj=conj)

Array([0.+0.j, 0.+0.j, 1.+0.j], dtype=complex128)

In [122]:
dDW_c(z,cz,tau,ctau,1,conj=conj)

Array([[2.-4.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]], dtype=complex128)

In [22]:
model.kahler_metric(z,cz,tau,ctau)-jnp.conj(model.kahler_metric(z,cz,tau,ctau).T)

Array([[ 0.0000000e+00-1.38777878e-17j,  6.9388939e-18+3.46944695e-18j,
         0.0000000e+00+0.00000000e+00j],
       [-6.9388939e-18+3.46944695e-18j,  0.0000000e+00-3.12250226e-17j,
         0.0000000e+00+0.00000000e+00j],
       [ 0.0000000e+00+0.00000000e+00j,  0.0000000e+00+0.00000000e+00j,
         0.0000000e+00+0.00000000e+00j]], dtype=complex128)

In [3]:
DDW = model.DDW_general(z,cz,tau,ctau,f)

TODO: TEST AND ADD COMPLEX CONJUGATE!!
SIMPLIFY???
IS THIS FUNCTION CORRECT?
Can we check the alternative implementation dDW+dK*W?
TODO: TEST AND ADD COMPLEX CONJUGATE!!
TODO: CHECK OUTER PRODUCT!!
TODO: TEST AND ADD COMPLEX CONJUGATE!!
Is this function (and its derivatives) faster when                we use the expression in terms of  prepotential????
TODO: TEST AND ADD COMPLEX CONJUGATE!!
TODO: TEST AND ADD COMPLEX CONJUGATE!!
TODO: TEST AND ADD COMPLEX CONJUGATE!!
TODO: TEST AND ADD COMPLEX CONJUGATE!!
TODO: TEST AND ADD COMPLEX CONJUGATE!!
TODO: TEST AND ADD COMPLEX CONJUGATE!!


In [16]:
DDW_mod = model.dDW(z,cz,tau,ctau,f)+jnp.outer(model.DW(z,cz,tau,ctau,f),model.dK(z,cz,tau,ctau))

In [17]:
DDW,DDW_mod

(Array([[-1.58436694e+02-4.09453407e+01j, -1.80533145e+04-4.37528678e+03j,
         -1.08759070e+03-1.95797956e+03j],
        [-1.80533145e+04-4.37528678e+03j, -1.63734541e+06-4.59634320e+05j,
         -1.54693697e+05-1.77454392e+04j],
        [-1.08759070e+03-1.95797956e+03j, -1.54693697e+05-1.77454392e+04j,
         -5.18968707e+04+1.05970593e+04j]], dtype=complex128),
 Array([[-1.58436694e+02-4.09453407e+01j, -1.80533145e+04-4.37528678e+03j,
         -1.08759070e+03-1.95797956e+03j],
        [-1.80533145e+04-4.37528678e+03j, -1.63734541e+06-4.59634320e+05j,
         -1.54693697e+05-1.77454392e+04j],
        [-1.08759070e+03-1.95797956e+03j, -1.54693697e+05-1.77454392e+04j,
         -5.18968707e+04+1.05970593e+04j]], dtype=complex128))

In [18]:
DDW-DDW_mod

Array([[-1.70530257e-13+2.84217094e-13j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00-5.82076609e-11j,
         0.00000000e+00+0.00000000e+00j],
       [-1.81898940e-12-1.36424205e-12j,  0.00000000e+00-1.45519152e-11j,
         0.00000000e+00-1.81898940e-12j]], dtype=complex128)